### ISSUE TITLE
Permissions in laravel

### ISSUE THREAD

**Issue by sinnbeck** [team23/b5#1]
Just giving this a try. Added b5 to an existing laravel project that was running homestead (and worked perfectly).

I followed the guide here but changed some paths etc.
https://christlieb.eu/blog/b5-example-project-with-laravel

I got it almost working but I am getting
```
The stream or file "/app/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
```

The issue seems to be that docker runs with a wrong user, and therefor it cannot read/write to my storage directory.

I would rather not give full permissions to the directory.

Is it perhaps to do with me not having my project in ./web? As it is an existing project, I have added the directory ./build inside my laravel root folder. I would prefer if I didn't have to move the project inside a new folder :)

Edit: Tried from scratch and this time I symlinked the project into ./web to keep with your folder structure.. I also tried following your guide to the point (new laravel installation and all). Sadly it changed nothing.

**Comment by bambamboole** [comment]
Do you run this on Linux or macOS? It seems like you are using Linux which does not pass the correct uid to the container. 
A possible workaround is to change the folder permissions to 777 and if you do not want to commit the file permission changes you can execute this git command:
```
git config core.fileMode false
```

If you are running macOS and have this issue would set up a example project on Github which you can check. Just give me some feedback :-)

**Comment by sinnbeck** [comment]
You are indeed correct regarding linux. I am running Ubuntu :)
I am considering using my own Dockerfile and then set ownership manually in there instead.

**Comment by bambamboole** [comment]
Okay just do this. A simple way is to get the UID 33 in you host system. This is the uid of all the www-data users in any Debian/Ubuntu based image.
Another option is to set the uid in the container via the entrypoint based on an environment variable.
Here's a link for this: https://boxboat.com/2017/07/25/fixuid-change-docker-container-uid-gid/

**Comment by sinnbeck** [comment]
Thanks! I will try implementing this in my setup :)

**Comment by sinnbeck** [comment]
I had a few issues geting fixuid to work properly so I just passed in my own UID and GID, and then created a user with this UID/GID, and changed FPM to run using this user :)

```
groupadd -g $GID robot
useradd -g $GID -d /home/robot -m -s /usr/sbin/nologin -u $UID robot

sed -r -i 's/^((user|group) = ).*$/\1robot/' /usr/local/etc/php-fpm.d/*

**Comment by bambamboole** [comment]
Thank you for the feedback :-)

**Comment by mmunz** [comment]
@Sinnbeck After a lot of other approaches i think what works best is using ACL. This is brandnew as i reworked it a bit with @bambamboole just now, but seems to get the job done:

```
USERID="$(id -u)"
sudo setfacl -dRm u:${USERID}:rwx project-path/
sudo setfacl -Rm u:${USERID}:rwx project_path/
```

This will add your User as (an additional) owner of all files and directories. The first line with (setfacl -dRm) sets the defaults for newly created files/directories. The second line adds the actual user as owner using Linux ACLs:

 
```
# $ :> getfacl web/
```

> \# file: web/
> \# owner: www-data
> \# group: www-data
> user::rwx
> **user:soma:rwx**
> group::rwx
> mask::rwx
> other::r-x
> default:user::rwx
> **default:user:soma:rwx**
> default:group::rwx
> default: mask::rwx
> default:other::r-x


As b5 task:

```
task:permissions:setacl() {
    # on linux: set extended ACL to make the current user also an owner of this project
    [ "$(uname -s)" = "Linux" ] || return 0

    SETFACL="$(which setfacl)"

    if [ -z "$SETFACL" ]; then
        echo "Error: setfacl binary not found, not setting ACLs!"
    fi

    if [ -n "$SETFACL" ]; then
        USERID="$(id -u)"
        docker:container_run --no-deps -w /app/ php setfacl -dRm u:${USERID}:rwx  /app
        docker:container_run --no-deps -w /app/ php setfacl -Rm u:${USERID}:rwx  /app
    fi
}
```
