### ISSUE TITLE
CONFIG_ env in docker compose

### ISSUE THREAD

**Issue by sinnbeck** [team23/b5#2]
Getting more and more happy for this little tool. Fits well into our pipeline :)

Anwyays.
Is there any way of using the CONFIG_ environment variables set in config, inside of docker-compose.yml? I am using the nginx proxy docker image and to connect to it from my container, I need to set VIRTUAL_HOST in environment. I was hoping that I could load this from the config file, enabling our developers to use custom domain if needed.

If I try this
```
environment:
            VIRTUAL_HOST: ${CONFIG_project_url} // I have tried with $CONFIG_project_url as well
            VIRTUAL_PORT: 80
```
 I just get 
```
WARNING: The CONFIG_project_url variable is not set. Defaulting to a blank string.

**Comment by ddanier** [comment]
You could use `export` to make the ENV variable available in commands you are calling inside the Taskfile.

https://www.tldp.org/LDP/abs/html/abs-guide.html#EXPORTREF

**Comment by sinnbeck** [comment]
Oh. I was hoping there was a build in way. Is there some way to get the config from inside a task?

Something like one of these (none of these work)
```
task:test() {
    echo $CONFIG_version
    echo ${CONFIG_version}
    echo $config.version
    echo $config:version
}

**Comment by sinnbeck** [comment]
Nevermind. It works in the tasks file. Tested using version but had not set it in my config! :(
This works :)
```
task:run() {
    export HOST_UID=$(id -u)
    export HOST_GID=$(id -g)
    export HOST_NAME=${CONFIG_project_hostname}
    docker:docker-compose up "$@"
}

**Comment by ddanier** [comment]
Great ;-)

btw. the docker module does by itself provide these ENV variables:
```
$COMPOSE_PROJECT_NAME
$DOCKER_HOST_SYSTEM
$DOCKER_HOST_USERNAME
$DOCKER_HOST_UNIX_UID
$DOCKER_HOST_UNIX_GID
```

see https://github.com/team23/b5/blob/master/docs/modules/docker.md#additional-environment-provided-when-using-dockerrun

**Comment by sinnbeck** [comment]
Sweet. That is indeed helpful :)
