### ISSUE TITLE
Multiple task names

### ISSUE THREAD

**Issue by sinnbeck** [team23/b5#3]
Just a suggestion

Allow tasks to respond to multiple names

For instance we have `task:halt` to stop docker. But some people are used to `docker-compose down`, meaning to make it work with both I need two identical tasks
My idea is therefor something like this to allow it to respond to multiple task names

```
task:halt|down() {
    docker:docker-compose down "$@"
}

**Comment by bambamboole** [comment]
hmm this would end up in more parsing which leads to more errors. It would maybe also break the execution of other tasks inside the taskfile. I would recommend to add a new task which executes the other task:
```
task:halt() {
    docker:docker-compose down "$@"
}
task:down() {
    task:halt "$@"
}
```

@ddanier fyi

**Comment by ddanier** [comment]
Hi @Sinnbeck,

thanks for this great idea!

As @bambamboole already mentioned this would not work. b5 currently generates a bash script which is then executed. The Taskfile is just part of this generated bash script and thus must be valid bash at this point. Having multiple names is not a bash feature.

But you may setup an alias for the task like @bambamboole pointed out above. In addition you may just define your own set of default task names, like we did (see https://github.com/team23/b5/blob/master/docs/03_common_tasks.md). But this may be a documentation issue and not be consistent with what other users have done.

**Comment by sinnbeck** [comment]
Those are fair points :) Thanks for the replies
